# -*- coding: utf-8 -*-
"""helloworld_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IEgBiem_KxDxaoMlR8YMNDReRdd5uNBY
"""

print('Hello  World!')